### ISSUE TITLE
Causing issue

### ISSUE THREAD

**Issue by James-Fire** [theRustyKnife/rusty-locale#7]
34.369 Error ModManager.cpp:1560: Failed to load mod "fire-replicators": __rusty-locale__/prototypes.lua:48: No prototype called `Matter-Converter-1` found for type `entity`, these prototypes with the name exist: {"item"}
Please report this to https://mods.factorio.com/mod/rusty-locale
stack traceback:
	[C]: in function 'error'
	__rusty-locale__/prototypes.lua:48: in function 'find'
	__rusty-locale__/locale.lua:42: in function 'f'
	__rusty-locale__/util.lua:10: in function '__index'
	__rusty-locale__/locale.lua:50: in function 'f'
	__rusty-locale__/util.lua:10: in function '__index'
	__rusty-locale__/locale.lua:66: in function 'f'
	__rusty-locale__/util.lua:10: in function '__index'
	__crafting_combinator__/data-final-fixes.lua:151: in function 'make_signal_for_recipe'
	__crafting_combinator__/data-final-fixes.lua:165: in function 'process_recipe'
	__crafting_combinator__/data-final-fixes.lua:201: in function 'hook'
	__crafting_combinator__/data-final-fixes.lua:12: in function '__newindex'
	__core__/lualib/dataloader.lua:31: in function 'extend'
	__fire-replicators__/prototypes/Replication Generation.lua:348: in function 'addMatterConverter'
	__fire-replicators__/prototypes/Replication Generation.lua:728: in main chunk
	[C]: in function 'require'
	__fire-replicators__/data-final-fixes.lua:1: in main chunk
	
The crux of the issue appears to be that your mod is somehow checking for these before they're even made. I use a script to generate a item, recipe, and entity for this, in that order. This error pops up before my script finishes and logs that they're complete.

**Comment by theRustyKnife** [comment]
I know im a bit late to this and its probably not really relevant anymore, but for some closure: This is more of a crafting combinator issue. It does a lot of trickery to catch every recipe being created, even ones that get added after it's data-final-fixes runs, such as in this case. This was necessary because a lot of mods do stupid things. I don't know if that was the case here, but it's just another case that needs handling for this - it should wait for the associated item and entity to be created if it fails like this.

With that said, crafting combinator will probably no longer be a thing with 2.0, and this library might meet a similar fate if raiguard adds it's functionality to flib, so all of the above is moot anyway.
